# Generated by Django 2.1.5 on 2019-02-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190208_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='name',
        ),
    ]
