# Generated by Django 2.1.5 on 2019-02-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gift_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='clothes_to_us',
            new_name='clothes_to_use',
        ),
    ]
