# Generated by Django 2.1.5 on 2019-02-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190213_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Institution'),
        ),
    ]
