# Generated by Django 2.1.5 on 2019-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_institution_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
