# Generated by Django 2.1.5 on 2019-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190219_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
